export interface Profile {
  id: string
  display_name: string
  avatar_color: string
  created_at: string
}

export interface LearningProgress {
  id: string
  user_id: string
  stage_id: number
  completed: boolean
  stars: number
  best_wpm: number
  best_accuracy: number
  completed_at?: string
  created_at: string
}

export interface GameScore {
  id: string
  user_id: string
  stage_id: number
  game_type: string
  wpm: number
  accuracy: number
  score: number
  duration: number
  created_at: string
  profiles?: Profile
}

export interface Stage {
  id: number
  title: string
  description: string
  icon: string
  content: string[]
  targetWpm: number
  targetAccuracy: number
}

export const STAGES: Stage[] = [
  {
    id: 1,
    title: "Home Row Keys",
    description: "Learn the basic finger positions",
    icon: "🏠",
    content: [
      // Single letters
      "a",
      "s",
      "d",
      "f",
      "j",
      "k",
      "l",
      // Two letters
      "as",
      "df",
      "jk",
      "sa",
      "fd",
      "kj",
      // Three letters
      "asd",
      "jkl",
      "dsa",
      "lkj",
      "asf",
      "jkl",
      // Four letters
      "asdf",
      "jkl;",
      "fdsa",
      ";lkj",
      "asjk",
      "dfkl",
      // Five letters
      "asdfj",
      "jkl;a",
      "fdsak",
      "lkjfd",
      // Six+ letters
      "asdfjk",
      "jkl;as",
      "asdfgh",
      "jkl;df",
      "asdfjkl;",
      "fdsajkl;",
      // Mixed patterns
      "aaa",
      "sss",
      "fff",
      "jjj",
      "kkk",
      "asas",
      "dfdf",
      "jkjk",
      "asdsa",
      "jklkj",
      "afaf",
      "jaja",
      "sksk",
      "dldl",
    ],
    targetWpm: 15,
    targetAccuracy: 90,
  },
  {
    id: 2,
    title: "All Letters",
    description: "Practice the entire alphabet",
    icon: "🔤",
    content: [
      // Single letters
      "a",
      "b",
      "c",
      "d",
      "e",
      "f",
      "g",
      "h",
      "i",
      "j",
      "k",
      "l",
      "m",
      "n",
      "o",
      "p",
      "q",
      "r",
      "s",
      "t",
      "u",
      "v",
      "w",
      "x",
      "y",
      "z",
      // Two letters
      "ab",
      "cd",
      "ef",
      "gh",
      "ij",
      "kl",
      "mn",
      "op",
      "qr",
      "st",
      "uv",
      "wx",
      "yz",
      // Three letters
      "the",
      "and",
      "for",
      "are",
      "but",
      "not",
      "you",
      "all",
      "can",
      "her",
      "was",
      "one",
      "our",
      "out",
      "day",
      "get",
      "has",
      "him",
      "his",
      "how",
      "man",
      "new",
      "now",
      "old",
      "see",
      "two",
      "way",
      "who",
      "boy",
      "did",
      "its",
      "let",
      "put",
      "say",
      "she",
      "too",
      "use",
      // Four letters
      "that",
      "with",
      "have",
      "this",
      "will",
      "your",
      "from",
      "they",
      "know",
      "want",
      "been",
      "good",
      "much",
      "some",
      "time",
      "very",
      "when",
      "come",
      "here",
      "just",
      "like",
      "long",
      "make",
      "many",
      "over",
      "such",
      "take",
      "than",
      "them",
      "well",
      "only",
      // Five+ letters
      "about",
      "after",
      "again",
      "could",
      "every",
      "first",
      "found",
      "great",
      "house",
      "large",
      "learn",
      "never",
      "other",
      "place",
      "plant",
      "point",
      "right",
      "small",
      "sound",
      "spell",
      "still",
      "study",
      "their",
      "there",
      "these",
      "thing",
      "think",
      "three",
      "water",
      "where",
      "which",
      "world",
      "would",
      "write",
      "years",
    ],
    targetWpm: 25,
    targetAccuracy: 92,
  },
  {
    id: 3,
    title: "Simple Words",
    description: "Type common words",
    icon: "📝",
    content: [
      // Two words
      "hello world",
      "good morning",
      "good night",
      "thank you",
      "see you",
      "bye bye",
      "yes please",
      "no thanks",
      "my name",
      "your turn",
      "our team",
      "his book",
      "her cat",
      "big dog",
      "red car",
      "blue sky",
      "green tree",
      "happy day",
      "sad face",
      "fast run",
      "slow walk",
      "hot sun",
      "cold ice",
      "new toy",
      "old house",
      // Three words
      "have a day",
      "see you later",
      "how are you",
      "what is this",
      "where are we",
      "when will you",
      "why did he",
      "I love you",
      "we are here",
      "they can go",
      "she is nice",
      "he is tall",
      "it is fun",
      "let us play",
      "come with me",
      "go to school",
      "read a book",
      "write a letter",
      "draw a picture",
      "sing a song",
      "play a game",
      "eat some food",
      "drink some water",
      "take a rest",
      "make a wish",
      // Four+ words
      "I want to learn",
      "she likes to read",
      "he can run fast",
      "we will go home",
      "they are my friends",
      "this is a cat",
      "that is a dog",
      "here is your book",
      "there is a bird",
      "where is my pen",
      "what do you want",
      "how can I help",
      "when will we start",
      "why are you here",
      "I am very happy",
      "you are so kind",
      "it is a nice day",
      "the sun is bright",
      "the moon is round",
      "the stars are shining",
    ],
    targetWpm: 35,
    targetAccuracy: 94,
  },
  {
    id: 4,
    title: "Sentences",
    description: "Practice full sentences",
    icon: "📖",
    content: [
      "The cat sat on the mat.",
      "I love to read books.",
      "She plays the piano well.",
      "We went to the park today.",
      "He likes to eat apples.",
      "They are going to school.",
      "My dog is very friendly.",
      "The bird sings every morning.",
      "I can swim in the pool.",
      "She draws beautiful pictures.",
      "We play games after school.",
      "The sun shines brightly today.",
      "I have a red bicycle.",
      "He writes stories every day.",
      "They enjoy playing outside.",
      "The flowers smell so sweet.",
      "I want to learn new things.",
      "She helps her mom at home.",
      "We eat dinner together.",
      "The rainbow has many colors.",
      "I brush my teeth twice daily.",
      "He runs faster than me.",
      "They share toys with friends.",
      "The moon comes out at night.",
      "I like to watch the clouds.",
      "She reads before going to bed.",
      "We listen to music together.",
      "The tree has green leaves.",
      "I count from one to ten.",
      "He knows all the answers.",
      "They laugh at funny jokes.",
      "The baby sleeps in the crib.",
      "I wear my favorite shirt.",
      "She bakes cookies on weekends.",
      "We visit grandma every month.",
      "The fish swim in the pond.",
      "I practice typing every day.",
      "He builds towers with blocks.",
      "They plant seeds in spring.",
      "The wind blows through the trees.",
    ],
    targetWpm: 45,
    targetAccuracy: 95,
  },
  {
    id: 5,
    title: "Speed Challenge",
    description: "Master your typing speed",
    icon: "⚡",
    content: [
      "The quick brown fox jumps over the lazy dog.",
      "Practice makes perfect when learning to type.",
      "Typing fast requires patience and dedication.",
      "Every student should learn to type properly.",
      "Good typing skills help in many ways.",
      "I enjoy typing because it is fun and useful.",
      "She types faster than anyone in her class.",
      "We practice typing for thirty minutes daily.",
      "The keyboard has many keys to remember.",
      "Learning to type takes time and effort.",
      "He can type without looking at the keys.",
      "They compete in typing speed contests.",
      "My goal is to type sixty words per minute.",
      "The teacher says practice is very important.",
      "I will keep practicing until I improve.",
      "She started slow but now types very fast.",
      "We should focus on accuracy before speed.",
      "The best typists practice every single day.",
      "I feel proud when I type without mistakes.",
      "He uses all ten fingers when typing.",
      "They learned proper finger placement first.",
      "My typing speed improves with each session.",
      "The computer helps us practice our skills.",
      "I can type many words in one minute now.",
      "She never gives up even when it is hard.",
      "We celebrate our progress and achievements.",
      "The secret to fast typing is regular practice.",
      "I remember to sit up straight while typing.",
      "He keeps his eyes on the screen not keyboard.",
      "They encourage each other to do their best.",
    ],
    targetWpm: 60,
    targetAccuracy: 96,
  },
]
